version: '3.4'

services:
  flaskdockersetup:
    image: flaskdockersetup
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./uploads:/app/uploads
